{{- $ca := genCA "admission-controller-ca" 3650 }}
{{- $cn := printf "%s-%s" .Release.Name .Chart.Name }}
{{- $altName1 := (list .Values.appname .Release.Namespace "svc" | join ".") }}
{{- $cert := genSignedCert $cn nil (list $altName1) 3650 $ca }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.appname }}-webhook-cfg
  namespace: {{ .Values.namespace }}
webhooks:
  - clientConfig:
      service:
        name: {{ .Values.appname }}
        namespace: {{ .Values.namespace }}
        path: /mutate
      caBundle: {{ b64enc $ca.Cert }}
    failurePolicy: Fail
    name: {{ .Values.appname }}.sfdc.internal
    namespaceSelector:
      matchExpressions:
        - key: sidecar-injection
          operator: NotIn
          values: ["disabled"]
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-certificate
  namespace: {{ .Values.namespace }}
data:
  cert.pem: {{ b64enc $cert.Cert }}
  key.pem: {{ b64enc $cert.Key }}
